# sqlite: &sqlite
  # adapter: sqlite3
  # database: db/<%= Rails.env %>.sqlite3

# mysql: &mysql
  # adapter: mysql2
  # database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  # username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  # password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  # host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  # port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME'] || 'culturartweb' %>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] || 'admindm2b4yw' %>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] || 'tujwgJbhwkdz' %>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST'] || '127.0.0.1' %>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT'] || '5433' %>
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>

#Comentar y descomentar el bloque development segun convenga
# development:
  # adapter: postgresql
  # encoding: utf8
  # database: culturart_development
  # pool: 5
  # username: culturart
  # password: 5133264991

#Comentar y descomentar el bloque development segun convenga
development:
  <<: *defaults

# #NET START postgresql-x64-9.3
# test: &test
  # <<: *defaults

production:
  <<: *defaults
